/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32f7xx.h"
#include "rcc.h"

int main(void)
{
	init_RCC();
    RCC->AHB1ENR |= RCC_AHB1ENR_GPIOBEN; // Включаем разрешение тактирование порта GPIOB
    GPIOB->MODER |= 1 << GPIO_MODER_MODER0_Pos; // Включаем General purpose output mode для PB0

    /* Loop forever */
    for(;;)
    {
        for(int i = 0; i < 100000; i++);
        /* Осуществляем сдвиг на заданную маску PB0 и исключающем или меняем значения PB0
         * ODR0 = 0, следовательно 0 ^ 1 = 1 и т.д.*/
        GPIOB->ODR ^= 1 << GPIO_ODR_OD0_Pos;
    }
}
